% code generated by ChatGPT

% Frequency values in Hz
frequency = [10, 30, 100, 300, 1e3, 10e3, 30e3, 100e3, 300e3, 1e6, 2e6, 5e6, 10e6]; 

% Magnitude in dB
gain_magnitude_dB = [3.39, 14.1, 22.3, 24.4, 24.8, 24.9, 24.8, 24.8, 24.7, 24.1, 22.6, 17.9, 12.4];

% Plot using semilogx for a logarithmic frequency scale
figure;
semilogx(frequency, gain_magnitude_dB, '-o', 'LineWidth', 1.5, 'MarkerSize', 6);

% Adjust Y-axis limits to give more space
ylim([0 30]);

% Labels and title
xlabel('Frequency (Hz)');
ylabel('Gain Magnitude dB');
title('Gain Magnitude versus Frequency of a BJT Amplifier – Brodric Young');

% Grid for better readability
grid on;
